# 2. Torch 사용법

### Torch
: facebook에서 제공하는 딥러닝 도구로서, numpy와 효율적인 연동을 지원하는 편리한 도구

- pytorch의 기본적인 data structure: tensor
- tensor: **2차원 이상의 array**이며 matrix, vector의 일반화된 객체이다
  - vector: 1차원 tensor
  - matrix: 2차원 tensor
  - RGB: 3차원 tensor



### Numpy
: 다차원 배열을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬의 패캐지

- Numpy를 사용하는 이유는 무엇일까?
  - 컴퓨터는 0과 1 밖에 이해할 수 없음. + 데이터를 숫자의 데이터로 볼 수 있음 </br>
  => 컴퓨터가 이해할 수 있도록 데이터를 숫자 형식으로 변환 </br>
  => 효율적으로 배열을 저장하고 조작하기 위해 만들어진 패키지 == <b>Numpy</b> </br>

## Tensor 생성

In [5]:
import torch

#### Array의 tensor 생성

In [6]:
V_data = [1., 2., 3.] # float 형태의 vector 생성
V = torch.tensor(V_data) # vector를 tensor로 만들기
print(V)

tensor([1., 2., 3.])


### Matrix의 tensor 생성

In [7]:
M_data = [[1., 2., 3.], [4., 5., 6.]] # flot 형태의 matrix 생성
M = torch.tensor(M_data) # matrix를 tensor로 만들기 
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Tensor 슬라이싱 및 인덱싱

In [22]:
print("==== 인덱싱 ====")
print("V = ", V)
print("V[0] =", V[0])
print("M = ", M)
print("M[0]", M[0])
print("M[0][0]", M[0][0])
print("\n")
print("==== 슬라이싱 ====")
print("M[:,0]", M[:,0])

==== 인덱싱 ====
V =  tensor([1., 2., 3.])
V[0] = tensor(1.)
M =  tensor([[1., 2., 3.],
        [4., 5., 6.]])
M[0] tensor([1., 2., 3.])
M[0][0] tensor(1.)


==== 슬라이싱 ====
M[:,0] tensor([1., 4.])


## 데이터 타입
tensor의 기본적인 타입: float </br>
데이터 타입을 int, double로 바꾸면 datatype이 같이 출력

In [26]:
x_data = torch.tensor([1., 2., 3.], dtype=torch.double)
print(x_data)

y_data = torch.tensor([1., 2., 3.], dtype=torch.int)
print(y_data)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)


## 가우시안 N(0, 1) 생성
tensor를 0 ~ 1 사이의 값으로 랜덤하게 생성한다 </br>
가우시안 분포인 만큼 평균과 표준편차를 이용해 분포를 변경할 수 있다.

In [27]:
x = torch.randn((3, 4, 5)) # 4행 5열의 matrix를 3개 생성
print(x)

tensor([[[ 1.2021, -0.9456, -0.8249, -0.9530,  1.6120],
         [-0.2300,  0.6870, -0.3944,  0.7063,  1.2062],
         [ 0.6949, -0.1663,  2.2758, -0.3043, -1.2322],
         [ 0.1712,  0.4423,  0.9707, -0.2349,  1.2608]],

        [[-1.3586,  0.4789, -0.0512, -0.4862, -1.3730],
         [ 0.0304, -0.1692, -1.7513, -0.7019,  0.1418],
         [-0.9333, -1.1728,  1.0924, -1.3813,  1.8609],
         [-0.0064,  0.4476,  0.4433,  0.2641,  0.6308]],

        [[ 0.3572, -0.1435,  0.6831, -0.2478, -0.1579],
         [-0.5053,  0.1056,  0.1940, -0.2029, -0.5433],
         [-1.0774, -1.3988,  0.3739, -1.4813,  0.0348],
         [ 0.4219, -0.3261,  1.7257, -1.4565,  0.8948]]])
